### ISSUE TITLE
Show existing date for puzzle in the Date picker.

### ISSUE THREAD

**Issue by MAHBUB-99** [farhan19999/Programming-For-Kids#9]
```
//TODO:
```

https://github.com/farhan19999/Programming-For-Kids/blob/78d941989ccd3938f301fbc0e23df32d45c4631e/frontend/src/pages/admin/admin_puzzle_modify/AdminPuzzleModify.jsx#L6

**Comment by farhan19999** [comment]
Used DatePicker from mui.
